# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FacebookLoginSample' do
  use_frameworks!

  # Pods for FacebookLoginSample
  pod 'RealmSwift'
  pod 'R.swift'

end
